test_that("default_single_row_output helper gives expected output in the considered cases", {
  index = 2:6 # index of the scoring
  o1 = default_single_row_output(0, 1, index, levels = NA)
  o2 = default_single_row_output(0, 1, index, levels = 1:4)
  o3 = default_single_row_output(+Inf, 0, index, levels = NA)
  o4 = default_single_row_output(+Inf, 0, index, levels = 1:4)
  expect_equal(class(o1), "data.frame")
  expect_equal(class(o2), "data.frame")
  expect_equal(class(o3), "data.frame")
  expect_equal(class(o4), "data.frame")
  my_colnames = c("selection_threshold_included", "selection_level", "selection", "selection_additional")
  expect_equal(colnames(o1), my_colnames)
  expect_equal(colnames(o2), my_colnames)
  expect_equal(colnames(o3), my_colnames)
  expect_equal(colnames(o4), my_colnames)
  expect_equal(nrow(o1), 1)
  expect_equal(nrow(o2), 4)
  expect_equal(nrow(o3), 1)
  expect_equal(nrow(o4), 4)
  expect_equal(o1$selection_threshold_included, 0)
  expect_equal(o2$selection_threshold_included, rep(0,4))
  expect_equal(o3$selection_threshold_included, +Inf)
  expect_equal(o4$selection_threshold_included, rep(+Inf,4))
  expect_equal(o1$selection_level, NA)
  expect_equal(o2$selection_level, 1:4)
  expect_equal(o3$selection_level, NA)
  expect_equal(o4$selection_level, 1:4)
  expect_equal(colnames(o1$selection[[1]]), c("index", "predictions"))
  expect_equal(colnames(o2$selection[[1]]), c("index", "predictions"))
  expect_equal(colnames(o3$selection[[1]]), c("index", "predictions"))
  expect_equal(colnames(o4$selection[[1]]), c("index", "predictions"))
})

test_that("multithreshold_default_inf is correct", {
  scoring = data.frame(index = 2:5, score = 2:5)
  output = multithreshold_default_inf(scoring, nb_levels = 4, cost_initial = 230)
  my_colnames = c("selection_threshold_included", "selection_level", "selection", "selection_additional")
  my_colnames2 = c("index", "predictions")

  expect_equal(class(output), "data.frame")
  expect_equal(colnames(output), my_colnames)
  expect_equal(nrow(output), 4)
  expect_equal(output$selection_threshold_included, rep(+Inf, 4))
  expect_equal(output$selection_level, 1:4)
  expect_equal(colnames(output$selection[[1]]), my_colnames2)
  expect_equal(output$selection_additional[[1]]$threshold_level, 1)
  # nrow is one below because there is 1 interval only since no cut at all
  expect_equal(nrow(output$selection_additional[[1]]$partitions[[1]]), 1)
})

test_that("multithreshold_default_min is correct", {
  scoring = data.frame(index = 2:5, score = 2:5)
  output = multithreshold_default_min(scoring, nb_levels = 4, default_score = 0)
  my_colnames = c("selection_threshold_included", "selection_level", "selection", "selection_additional")
  my_colnames2 = c("index", "predictions")

  expect_equal(class(output), "data.frame")
  expect_equal(colnames(output), my_colnames)
  expect_equal(nrow(output), 4)
  expect_equal(output$selection_threshold_included, rep(0, 4))
  expect_equal(output$selection_level, 1:4)
  expect_equal(colnames(output$selection[[1]]), my_colnames2)
  expect_equal(output$selection_additional[[1]]$threshold_level, 1)
  expect_equal(nrow(output$selection_additional[[1]]$partitions[[1]]), nrow(scoring)+1)
})
